apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "mystatefulset.labels" . | nindent 4 }}
  name: {{ include "mystatefulset.fullname" . }}-mystatefulset-editor-role
rules:
- apiGroups:
  - workload.jojotong.io.jojotong.io
  resources:
  - mystatefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workload.jojotong.io.jojotong.io
  resources:
  - mystatefulsets/status
  verbs:
  - get