apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "mystatefulset.fullname" . }}-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "mystatefulset.fullname" . }}-webhook-service
      namespace: {{ include "mystatefulset.fullname" . }}-system
      path: /mutate-workload-jojotong-io-jojotong-io-v1-mystatefulset
  failurePolicy: Fail
  name: mmystatefulset.kb.io
  rules:
  - apiGroups:
    - workload.jojotong.io.jojotong.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - mystatefulsets
  sideEffects: None