---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-workload-jojotong-io-jojotong-io-v1-mystatefulset
  failurePolicy: Fail
  name: mmystatefulset.kb.io
  rules:
  - apiGroups:
    - workload.jojotong.io.jojotong.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - mystatefulsets
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-workload-jojotong-io-jojotong-io-v1-mystatefulset
  failurePolicy: Fail
  name: vmystatefulset.kb.io
  rules:
  - apiGroups:
    - workload.jojotong.io.jojotong.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - mystatefulsets
  sideEffects: None
